version: '3.8'

services:
  mysql:
    image: mysql:latest  # Use the latest MySQL image
    container_name: scheduler-mysql-container  # Name of the container
    environment:
      MYSQL_ROOT_PASSWORD: password  # Root user password
      MYSQL_DATABASE: scheduler  # Name of the default database
    ports:
      - "3306:3306"  # Map the MySQL default port to the host
    volumes:
      - scheduler_mysql_data:/var/lib/mysql  # Persist MySQL data
    networks:
      - scheduler_network  # Define the network


volumes:
  scheduler_mysql_data:
    driver: local  # Use a local volume for data persistence

networks:
  scheduler_network:
    driver: bridge